# Generated by Django 4.1.7 on 2023-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
